apiVersion: v1
kind: Pod
metadata:
  name: pod-redis
  labels:
    app: redis-app
    type: backend
spec:
  containers:
    - name: redis-container
      image: redis
      ports:
        - containerPort: 6379
