apiVersion: v1
kind: Pod
metadata:
  name: pod-busybox-1
  labels:
    app: busybox-app
spec:
  containers:
    - name: busybox-container
      image: busybox
      command: 
        - "/bin/sh"
        - "-c"
        - "echo Hello Kubernetes && sleep 3600"

