apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis
  namespace: dev
spec:
  containers:
  - image: redis
    name: redis
    resources:
      requests:
        memory: "1Gi"
        cpu: "100m"
      limits:
        memory: "2Gi"
        cpu: "200m"
