apiVersion: v1
kind: Service
metadata:
  name: service-redis
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
    nodePort: 30008
  selector:
    app: redis-app
    type: backend
