apiVersion: v1
kind: Service
metadata:
  name: service-nginx-1
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: nginx-app
